################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

# Production Flink Configuration

# JobManager Configuration
jobmanager.rpc.address: localhost
jobmanager.rpc.port: 6123
jobmanager.bind-host: 0.0.0.0
jobmanager.memory.process.size: 1600m
jobmanager.memory.flink.size: 1280m
jobmanager.memory.jvm-overhead.fraction: 0.1

# TaskManager Configuration
taskmanager.bind-host: 0.0.0.0
taskmanager.host: localhost
taskmanager.rpc.port: 6122
taskmanager.data.port: 6121
taskmanager.numberOfTaskSlots: 4
taskmanager.memory.process.size: 1728m
taskmanager.memory.flink.size: 1280m
taskmanager.memory.framework.heap.size: 128m
taskmanager.memory.task.heap.size: 512m
taskmanager.memory.managed.fraction: 0.4
taskmanager.memory.network.fraction: 0.1
taskmanager.memory.jvm-overhead.fraction: 0.1

# Parallelism
parallelism.default: 4

# Restart Strategy
restart-strategy: exponential-delay
restart-strategy.exponential-delay.initial-backoff: 10s
restart-strategy.exponential-delay.max-backoff: 2min
restart-strategy.exponential-delay.backoff-multiplier: 2.0
restart-strategy.exponential-delay.reset-backoff-threshold: 10min
restart-strategy.exponential-delay.jitter-factor: 0.1

# Checkpointing Configuration
state.backend: hashmap
state.checkpoints.dir: file:///opt/flink-apps/checkpoints
state.savepoints.dir: file:///opt/flink-apps/savepoints
state.backend.incremental: true
execution.checkpointing.interval: 60s
execution.checkpointing.mode: EXACTLY_ONCE
execution.checkpointing.timeout: 10min
execution.checkpointing.max-concurrent-checkpoints: 1
execution.checkpointing.min-pause: 30s
execution.checkpointing.prefer-checkpoint-for-recovery: true
execution.checkpointing.unaligned: false

# State Configuration
state.backend.rocksdb.memory.managed: true
state.backend.rocksdb.memory.fixed-per-slot: 128m
state.backend.rocksdb.checkpoint.transfer.thread.num: 4
state.backend.rocksdb.localdir: /tmp/rocksdb

# Network Configuration
taskmanager.network.memory.fraction: 0.1
taskmanager.network.memory.min: 64mb
taskmanager.network.memory.max: 1gb
taskmanager.network.detailed-metrics: false

# Web UI Configuration
web.address: 0.0.0.0
web.port: 8081
web.submit.enable: true
web.cancel.enable: true
web.checkpoints.history: 10
web.backpressure.cleanup-interval: 10min
web.backpressure.num-samples: 100
web.backpressure.delay: 50ms

# Metrics Configuration
metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
metrics.reporter.prom.port: 9249
metrics.reporters: prom

# Logging Configuration
log.file: /opt/flink-apps/logs/flink.log
rootLogger.level: INFO
rootLogger.appenderRef.console.ref: ConsoleAppender
rootLogger.appenderRef.rolling.ref: RollingFileAppender

# High Availability Configuration (for production clusters)
# high-availability: zookeeper
# high-availability.zookeeper.quorum: localhost:2181
# high-availability.storageDir: file:///opt/flink-apps/ha/
# high-availability.cluster-id: /default

# Security Configuration
security.ssl.enabled: false
security.ssl.keystore: /path/to/keystore
security.ssl.keystore-password: password
security.ssl.key-password: password
security.ssl.truststore: /path/to/truststore
security.ssl.truststore-password: password

# Table API Configuration
table.exec.state.ttl: 1d
table.exec.mini-batch.enabled: true
table.exec.mini-batch.allow-latency: 5s
table.exec.mini-batch.size: 5000
table.optimizer.join-reorder-enabled: true

# Watermark Configuration
pipeline.time-characteristic: EventTime
pipeline.auto-watermark-interval: 200ms

# Resource Configuration
cluster.fine-grained-resource-management.enabled: false
slotmanager.redundant-taskmanager-num: 0

# Blob Storage Configuration
blob.server.port: 6124
blob.service.cleanup.interval: 3600
blob.storage.directory: /tmp/blobStore

# History Server Configuration (optional)
# historyserver.web.address: 0.0.0.0
# historyserver.web.port: 8082
# historyserver.archive.fs.dir: file:///opt/flink-apps/completed-jobs
# historyserver.archive.fs.refresh-interval: 10000